---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: hello-app
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: hello-app
  chart:
    git: ssh://git@github.com/Masatoshi-Kouda/k8s-gitops-config
    ref: master
    path: charts/hello-app
  values:
    image:
      repository: asia.gcr.io/masatoshi-kouda-207408/golang-hello-app
      tag: dev-8c2bb0d223527d0298cc2883d2e20331177bdcaf
    replicaCount: 1
