apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: hello-app
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: hello-app
  chart:
    git: ssh://git@github.com/Masatoshi-Kouda/k8s-gitops-config
    ref: master
    path: charts/hello-app
  values:
    image:
      repository: masatoshi/golang-hello-app
      tag: 40c340bd89dbb0fd730685ca4b926f5acb5ae72f
