---
# Source: hello-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app.kubernetes.io/name: hello-app
    helm.sh/chart: hello-app-0.1.0
    app.kubernetes.io/instance: hello-app
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hello-app
    app.kubernetes.io/instance: hello-app
