---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
spec:
  selector:
    name: fluxcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3032
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      containers:
      - name: fluxcloud
        image: justinbarrick/fluxcloud:v0.3.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3032
        env:
        - name: SLACK_URL
          valueFrom:
            secretKeyRef:
              name: slack-url
              key: slack-url
        - name: SLACK_CHANNEL
          value: "#weave-flux"
        - name: SLACK_USERNAME
          value: Flux Deployer
        - name: SLACK_ICON_EMOJI
          value: ":weave-flux:"
        - name: GITHUB_URL
          value: "https://github.com/Masatoshi-Kouda/k8s-gitops-config"
        - name: LISTEN_ADDRESS
          value: ":3032"
